---
 services:
  nginx:
   build: ./nginx/
   container_name: nginx-container
   restart: always
   ports:
    - "8080:80"
   links:
    - php
    - mysql
   volumes_from:
    - app-data

  php:
   build: ./php/
   container_name: php-container
   expose:
    - 9000
   volumes_from:
    - app-data

  app-data:
   image: php:7.0-fpm
   container_name: app-data-container
   volumes:
    - ./www/:/var/www/html/
   command: "true"

  mysql:    
   build: ./mysql/   
   ports:
    - "3306:3306"
   container_name: mysql-container
   environment:  
    MYSQL_ROOT_PASSWORD: esbart  
    #MYSQL_DATABASE: esbart  
    #MYSQL_USER: esbart  
    #MYSQL_PASSWORD: aenae5Oaboo0SaiTheil8xieGhoo7igi  
   volumes_from:
    - mysql-data

  mysql-data:    
   image: mysql:5.7 
   container_name: mysql-data-container  
   volumes:  
    - /var/lib/mysql  
   command: "true"


 networks:
  mynet:



